
import { CandlestickPattern, PatternType, Trend } from './types';

export const CANDLESTICK_PATTERNS: CandlestickPattern[] = [
  // Single Candle Patterns
  {
    name: 'Long Green Candle',
    type: PatternType.BULLISH,
    trend: Trend.CONTINUATION,
    description: 'A long bullish candle indicating strong buying pressure and upward momentum.',
    candles: [{ open: 20, high: 85, low: 18, close: 83 }],
  },
  {
    name: 'Long Red Candle',
    type: PatternType.BEARISH,
    trend: Trend.CONTINUATION,
    description: 'A long bearish candle indicating strong selling pressure and downward momentum.',
    candles: [{ open: 83, high: 85, low: 18, close: 20 }],
  },
  {
    name: 'Short Green Candle',
    type: PatternType.BULLISH,
    trend: Trend.CONTINUATION,
    description: 'A short bullish candle showing mild buying pressure with limited momentum.',
    candles: [{ open: 45, high: 58, low: 43, close: 55 }],
  },
  {
    name: 'Short Red Candle',
    type: PatternType.BEARISH,
    trend: Trend.CONTINUATION,
    description: 'A short bearish candle showing mild selling pressure with limited momentum.',
    candles: [{ open: 55, high: 58, low: 43, close: 45 }],
  },
  {
    name: 'Green Marubozu',
    type: PatternType.BULLISH,
    trend: Trend.CONTINUATION,
    description: 'A long green candle with no wicks, showing strong bullish sentiment from open to close.',
    candles: [{ open: 20, high: 80, low: 20, close: 80 }],
  },
  {
    name: 'Red Marubozu',
    type: PatternType.BEARISH,
    trend: Trend.CONTINUATION,
    description: 'A long red candle with no wicks, showing strong bearish sentiment from open to close.',
    candles: [{ open: 80, high: 80, low: 20, close: 20 }],
  },
  {
    name: 'Bullish Spinning Top',
    type: PatternType.NEUTRAL,
    trend: Trend.INDECISION,
    description: 'A candle with a small green body and long wicks on both sides, indicating market indecision.',
    candles: [{ open: 48, high: 75, low: 25, close: 52 }],
  },
  {
    name: 'Bearish Spinning Top',
    type: PatternType.NEUTRAL,
    trend: Trend.INDECISION,
    description: 'A candle with a small red body and long wicks on both sides, indicating market indecision.',
    candles: [{ open: 52, high: 75, low: 25, close: 48 }],
  },

  // Doji Patterns
  {
    name: 'Doji',
    type: PatternType.NEUTRAL,
    trend: Trend.INDECISION,
    description: 'A candle where open and close are virtually equal, signifying market indecision.',
    candles: [{ open: 50, high: 70, low: 30, close: 50.5 }],
  },
  {
    name: 'Long Legged Doji',
    type: PatternType.NEUTRAL,
    trend: Trend.INDECISION,
    description: 'A doji with very long upper and lower wicks, showing extreme indecision and volatility.',
    candles: [{ open: 50, high: 85, low: 15, close: 50.5 }],
  },
  {
    name: 'Cross Doji',
    type: PatternType.NEUTRAL,
    trend: Trend.INDECISION,
    description: 'A perfect doji where open equals close, forming a cross shape indicating strong indecision.',
    candles: [{ open: 50, high: 65, low: 35, close: 50 }],
  },
  {
    name: 'Inverted Cross Doji',
    type: PatternType.NEUTRAL,
    trend: Trend.INDECISION,
    description: 'A doji with equal upper and lower wicks, showing balanced buying and selling pressure.',
    candles: [{ open: 50, high: 65, low: 35, close: 50 }],
  },
  {
    name: 'Dragonfly Doji',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A doji with a long lower wick and no upper wick, suggesting potential bullish reversal.',
    candles: [{ open: 70, high: 70, low: 30, close: 70 }],
  },
  {
    name: 'Gravestone Doji',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A doji with a long upper wick and no lower wick, suggesting potential bearish reversal.',
    candles: [{ open: 30, high: 70, low: 30, close: 30 }],
  },
  {
    name: 'Hammer',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern with a small body and long lower wick, forming during a downtrend.',
    candles: [{ open: 70, high: 72, low: 20, close: 68 }],
  },
  {
    name: 'Hanging Man',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern identical to hammer but appears during an uptrend.',
    candles: [{ open: 68, high: 72, low: 20, close: 70 }],
  },
  {
    name: 'Inverted Hammer',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern with a small body and long upper wick during a downtrend.',
    candles: [{ open: 30, high: 80, low: 28, close: 32 }],
  },
  {
    name: 'Shooting Star',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern identical to inverted hammer but appears during an uptrend.',
    candles: [{ open: 32, high: 80, low: 28, close: 30 }],
  },

  // Two Candle Patterns
  {
    name: 'Bullish Engulfing',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern where a large green candle completely engulfs the previous red candle.',
    candles: [
      { open: 60, high: 62, low: 50, close: 52 },
      { open: 48, high: 80, low: 46, close: 78 },
    ],
  },
  {
    name: 'Bearish Engulfing',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern where a large red candle completely engulfs the previous green candle.',
    candles: [
      { open: 52, high: 62, low: 50, close: 60 },
      { open: 78, high: 80, low: 46, close: 48 },
    ],
  },
  {
    name: 'Piercing Pattern',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern where a green candle opens below and closes above the midpoint of the previous red candle.',
    candles: [
      { open: 70, high: 72, low: 40, close: 42 },
      { open: 35, high: 68, low: 33, close: 65 },
    ],
  },
  {
    name: 'Dark Cloud Cover',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern where a red candle opens above and closes below the midpoint of the previous green candle.',
    candles: [
      { open: 42, high: 72, low: 40, close: 70 },
      { open: 75, high: 77, low: 45, close: 47 },
    ],
  },
  {
    name: 'Bullish Harami',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern where a small green candle is contained within the body of the previous large red candle.',
    candles: [
      { open: 80, high: 82, low: 30, close: 32 },
      { open: 45, high: 60, low: 43, close: 58 },
    ],
  },
  {
    name: 'Bearish Harami',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern where a small red candle is contained within the body of the previous large green candle.',
    candles: [
      { open: 32, high: 82, low: 30, close: 80 },
      { open: 58, high: 60, low: 43, close: 45 },
    ],
  },
  {
    name: 'Bullish Kicker',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A strong bullish reversal pattern with a gap up opening after a red candle.',
    candles: [
      { open: 70, high: 72, low: 40, close: 42 },
      { open: 75, high: 90, low: 73, close: 88 },
    ],
  },
  {
    name: 'Bearish Kicker',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A strong bearish reversal pattern with a gap down opening after a green candle.',
    candles: [
      { open: 42, high: 72, low: 40, close: 70 },
      { open: 35, high: 37, low: 15, close: 18 },
    ],
  },

  // Three Candle Patterns
  {
    name: 'Morning Star',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A three-candle bullish reversal pattern: large red candle, small-bodied candle, and large green candle.',
    candles: [
      { open: 80, high: 82, low: 30, close: 32 },
      { open: 22, high: 28, low: 18, close: 24 },
      { open: 35, high: 90, low: 33, close: 88 },
    ],
  },
  {
    name: 'Evening Star',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A three-candle bearish reversal pattern: large green candle, small-bodied candle, and large red candle.',
    candles: [
      { open: 35, high: 90, low: 33, close: 88 },
      { open: 95, high: 99, low: 92, close: 94 },
      { open: 80, high: 82, low: 30, close: 32 },
    ],
  },
  {
    name: 'Bullish Abandoned Baby',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A rare bullish reversal pattern with gaps on both sides of a doji, showing strong reversal.',
    candles: [
      { open: 70, high: 72, low: 30, close: 32 },
      { open: 20, high: 22, low: 18, close: 20 },
      { open: 35, high: 80, low: 33, close: 78 },
    ],
  },
  {
    name: 'Bearish Abandoned Baby',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A rare bearish reversal pattern with gaps on both sides of a doji, showing strong reversal.',
    candles: [
      { open: 32, high: 72, low: 30, close: 70 },
      { open: 80, high: 82, low: 78, close: 80 },
      { open: 65, high: 67, low: 20, close: 22 },
    ],
  },
  {
    name: 'Three White Soldiers',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern of three consecutive long green candles with higher opens and closes.',
    candles: [
      { open: 30, high: 55, low: 28, close: 53 },
      { open: 53, high: 78, low: 51, close: 76 },
      { open: 76, high: 100, low: 74, close: 98 },
    ],
  },
  {
    name: 'Three Black Crows',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern of three consecutive long red candles with lower opens and closes.',
    candles: [
      { open: 98, high: 100, low: 74, close: 76 },
      { open: 76, high: 78, low: 51, close: 53 },
      { open: 53, high: 55, low: 28, close: 30 },
    ],
  },
  {
    name: 'Inside Gap Two Crows',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish pattern with two red candles gapping up after a green candle, showing weakness.',
    candles: [
      { open: 30, high: 70, low: 28, close: 68 },
      { open: 75, high: 77, low: 60, close: 62 },
      { open: 65, high: 67, low: 45, close: 47 },
    ],
  },
  {
    name: 'Two Crows',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern with two consecutive red candles after a strong green candle.',
    candles: [
      { open: 30, high: 80, low: 28, close: 78 },
      { open: 82, high: 84, low: 65, close: 67 },
      { open: 70, high: 72, low: 50, close: 52 },
    ],
  },
  {
    name: 'Three Inside Up',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern starting with a harami followed by a confirming green candle.',
    candles: [
      { open: 80, high: 82, low: 30, close: 32 },
      { open: 45, high: 60, low: 43, close: 58 },
      { open: 60, high: 85, low: 58, close: 83 },
    ],
  },
  {
    name: 'Three Inside Down',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern starting with a harami followed by a confirming red candle.',
    candles: [
      { open: 32, high: 82, low: 30, close: 80 },
      { open: 58, high: 60, low: 43, close: 45 },
      { open: 43, high: 45, low: 20, close: 22 },
    ],
  },
  {
    name: 'Three Outside Up',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern starting with an engulfing followed by a confirming green candle.',
    candles: [
      { open: 60, high: 62, low: 50, close: 52 },
      { open: 48, high: 80, low: 46, close: 78 },
      { open: 80, high: 95, low: 78, close: 93 },
    ],
  },
  {
    name: 'Three Outside Down',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern starting with an engulfing followed by a confirming red candle.',
    candles: [
      { open: 52, high: 62, low: 50, close: 60 },
      { open: 78, high: 80, low: 46, close: 48 },
      { open: 46, high: 48, low: 25, close: 27 },
    ],
  },

  // Advanced Patterns
  {
    name: 'Bullish Tri-Star',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A rare bullish reversal pattern consisting of three doji candles.',
    candles: [
      { open: 50, high: 65, low: 35, close: 50 },
      { open: 30, high: 32, low: 28, close: 30 },
      { open: 50, high: 65, low: 35, close: 50 },
    ],
  },
  {
    name: 'Bearish Tri-Star',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A rare bearish reversal pattern consisting of three doji candles.',
    candles: [
      { open: 50, high: 65, low: 35, close: 50 },
      { open: 70, high: 72, low: 68, close: 70 },
      { open: 50, high: 65, low: 35, close: 50 },
    ],
  },
  {
    name: 'Three Stars In The South',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern with three consecutive red candles showing decreasing selling pressure.',
    candles: [
      { open: 70, high: 72, low: 20, close: 25 },
      { open: 30, high: 35, low: 22, close: 28 },
      { open: 32, high: 38, low: 30, close: 35 },
    ],
  },
  {
    name: 'Advance Block',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern with three green candles showing weakening momentum.',
    candles: [
      { open: 30, high: 70, low: 28, close: 68 },
      { open: 65, high: 80, low: 63, close: 78 },
      { open: 75, high: 85, low: 73, close: 83 },
    ],
  },
  {
    name: 'Bullish Stick Sandwich',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern with two red candles having the same close, separated by a green candle.',
    candles: [
      { open: 70, high: 72, low: 30, close: 32 },
      { open: 35, high: 75, low: 33, close: 73 },
      { open: 68, high: 70, low: 30, close: 32 },
    ],
  },
  {
    name: 'Bearish Stick Sandwich',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern with two green candles having the same close, separated by a red candle.',
    candles: [
      { open: 32, high: 72, low: 30, close: 70 },
      { open: 73, high: 75, low: 33, close: 35 },
      { open: 32, high: 72, low: 30, close: 70 },
    ],
  },
  {
    name: 'Matching Low',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern with two red candles having the same low, suggesting support.',
    candles: [
      { open: 70, high: 72, low: 30, close: 35 },
      { open: 65, high: 67, low: 30, close: 40 },
    ],
  },
  {
    name: 'Matching High',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern with two green candles having the same high, suggesting resistance.',
    candles: [
      { open: 35, high: 70, low: 30, close: 65 },
      { open: 40, high: 70, low: 35, close: 60 },
    ],
  },
  {
    name: 'Tweezers Bottom',
    type: PatternType.BULLISH,
    trend: Trend.REVERSAL,
    description: 'A bullish reversal pattern with two or more candles having the same low, indicating support.',
    candles: [
      { open: 60, high: 65, low: 20, close: 25 },
      { open: 30, high: 70, low: 20, close: 65 },
    ],
  },
  {
    name: 'Tweezers Top',
    type: PatternType.BEARISH,
    trend: Trend.REVERSAL,
    description: 'A bearish reversal pattern with two or more candles having the same high, indicating resistance.',
    candles: [
      { open: 25, high: 80, low: 20, close: 75 },
      { open: 70, high: 80, low: 35, close: 40 },
    ],
  },

  // Gap Patterns
  {
    name: 'Bullish Breakaway',
    type: PatternType.BULLISH,
    trend: Trend.CONTINUATION,
    description: 'A bullish continuation pattern with a gap that remains unfilled, showing strong momentum.',
    candles: [
      { open: 70, high: 72, low: 30, close: 32 },
      { open: 40, high: 45, low: 38, close: 43 },
      { open: 45, high: 50, low: 43, close: 48 },
      { open: 50, high: 55, low: 48, close: 53 },
      { open: 55, high: 80, low: 53, close: 78 },
    ],
  },
  {
    name: 'Bearish Breakaway',
    type: PatternType.BEARISH,
    trend: Trend.CONTINUATION,
    description: 'A bearish continuation pattern with a gap that remains unfilled, showing strong momentum.',
    candles: [
      { open: 32, high: 72, low: 30, close: 70 },
      { open: 60, high: 62, low: 55, close: 57 },
      { open: 55, high: 57, low: 50, close: 52 },
      { open: 50, high: 52, low: 45, close: 47 },
      { open: 45, high: 47, low: 20, close: 22 },
    ],
  },
  {
    name: 'Upside Tasuki Gap',
    type: PatternType.BULLISH,
    trend: Trend.CONTINUATION,
    description: 'A bullish continuation pattern where a gap up is partially filled but the trend continues.',
    candles: [
      { open: 30, high: 55, low: 28, close: 53 },
      { open: 60, high: 80, low: 58, close: 78 },
      { open: 70, high: 72, low: 45, close: 47 },
    ],
  },
  {
    name: 'Downside Tasuki Gap',
    type: PatternType.BEARISH,
    trend: Trend.CONTINUATION,
    description: 'A bearish continuation pattern where a gap down is partially filled but the trend continues.',
    candles: [
      { open: 78, high: 80, low: 58, close: 60 },
      { open: 53, high: 55, low: 28, close: 30 },
      { open: 47, high: 72, low: 45, close: 70 },
    ],
  },
  {
    name: 'Falling Three Method',
    type: PatternType.BEARISH,
    trend: Trend.CONTINUATION,
    description: 'A bearish continuation pattern with a long red candle, three small green candles, then another long red candle.',
    candles: [
      { open: 80, high: 82, low: 30, close: 32 },
      { open: 35, high: 45, low: 33, close: 43 },
      { open: 43, high: 50, low: 41, close: 48 },
      { open: 48, high: 55, low: 46, close: 53 },
      { open: 50, high: 52, low: 15, close: 17 },
    ],
  },
  {
    name: 'Rising Three Method',
    type: PatternType.BULLISH,
    trend: Trend.CONTINUATION,
    description: 'A bullish continuation pattern with a long green candle, three small red candles, then another long green candle.',
    candles: [
      { open: 32, high: 82, low: 30, close: 80 },
      { open: 75, high: 77, low: 65, close: 67 },
      { open: 65, high: 67, low: 55, close: 57 },
      { open: 55, high: 57, low: 45, close: 47 },
      { open: 50, high: 95, low: 48, close: 93 },
    ],
  },
  {
    name: 'Bearish Side By Side White Lines',
    type: PatternType.BEARISH,
    trend: Trend.CONTINUATION,
    description: 'A bearish continuation pattern with two green candles gapping down, showing weakness.',
    candles: [
      { open: 70, high: 72, low: 30, close: 32 },
      { open: 40, high: 60, low: 38, close: 58 },
      { open: 42, high: 62, low: 40, close: 60 },
    ],
  },
  {
    name: 'Bullish Side By Side White Lines',
    type: PatternType.BULLISH,
    trend: Trend.CONTINUATION,
    description: 'A bullish continuation pattern with two green candles gapping up, showing strength.',
    candles: [
      { open: 32, high: 72, low: 30, close: 70 },
      { open: 75, high: 85, low: 73, close: 83 },
      { open: 77, high: 87, low: 75, close: 85 },
    ],
  },
  {
    name: 'Gapping 2021',
    type: PatternType.NEUTRAL,
    trend: Trend.INDECISION,
    description: 'A modern pattern representing extreme volatility and gapping behavior seen in recent markets.',
    candles: [
      { open: 50, high: 55, low: 45, close: 52 },
      { open: 60, high: 65, low: 58, close: 62 },
      { open: 40, high: 45, low: 35, close: 42 },
      { open: 70, high: 75, low: 68, close: 72 },
      { open: 30, high: 35, low: 25, close: 32 },
    ],
  },
];
